package Services.SicrediAPITest.GET;

import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class AllProductsSearch {
    private static final String BASE_URI = "https://dummyjson.com/products";

    @Test
    public void testAllProductsSearch() {
        given()
                .when()
                .get(BASE_URI)
                .then()
                .statusCode(200)
                .body("products.size()", equalTo(30))

                .body("products[0].id", equalTo(1))
                .body("products[0].title", equalTo("iPhone 9"))
                .body("products[0].description", equalTo("An apple mobile which is nothing like apple"))
                .body("products[0].price", equalTo(549))
                .body("products[0].discountPercentage", equalTo(12.96f))
                .body("products[0].rating", equalTo(4.69f))
                .body("products[0].stock", equalTo(94))
                .body("products[0].brand", equalTo("Apple"))
                .body("products[0].category", equalTo("smartphones"))
                .body("products[0].thumbnail", equalTo("https://i.dummyjson.com/data/products/1/thumbnail.jpg"))
                .body("products[0].images.size()", equalTo(5))
                .body("products[0].images[0]", equalTo("https://i.dummyjson.com/data/products/1/1.jpg"))
                .body("products[0].images[1]", equalTo("https://i.dummyjson.com/data/products/1/2.jpg"))
                .body("products[0].images[2]", equalTo("https://i.dummyjson.com/data/products/1/3.jpg"))
                .body("products[0].images[3]", equalTo("https://i.dummyjson.com/data/products/1/4.jpg"))
                .body("products[0].images[4]", equalTo("https://i.dummyjson.com/data/products/1/thumbnail.jpg"))


                .body("products[1].id", equalTo(2))
                .body("products[1].title", equalTo("iPhone X"))
                .body("products[1].description", equalTo("SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ..."))
                .body("products[1].price", equalTo(899))
                .body("products[1].discountPercentage", equalTo(17.94f))
                .body("products[1].rating", equalTo(4.44f))
                .body("products[1].stock", equalTo(34))
                .body("products[1].brand", equalTo("Apple"))
                .body("products[1].category", equalTo("smartphones"))
                .body("products[1].thumbnail", equalTo("https://i.dummyjson.com/data/products/2/thumbnail.jpg"))
                .body("products[1].images.size()", equalTo(4))
                .body("products[1].images[0]", equalTo("https://i.dummyjson.com/data/products/2/1.jpg"))
                .body("products[1].images[1]", equalTo("https://i.dummyjson.com/data/products/2/2.jpg"))
                .body("products[1].images[2]", equalTo("https://i.dummyjson.com/data/products/2/3.jpg"))
                .body("products[1].images[3]", equalTo("https://i.dummyjson.com/data/products/2/thumbnail.jpg"))


                .body("products[2].id", equalTo(3))
                .body("products[2].title", equalTo("Samsung Universe 9"))
                .body("products[2].description", equalTo("Samsung's new variant which goes beyond Galaxy to the Universe"))
                .body("products[2].price", equalTo(1249))
                .body("products[2].discountPercentage", equalTo(15.46f))
                .body("products[2].rating", equalTo(4.09f))
                .body("products[2].stock", equalTo(36))
                .body("products[2].brand", equalTo("Samsung"))
                .body("products[2].category", equalTo("smartphones"))
                .body("products[2].thumbnail", equalTo("https://i.dummyjson.com/data/products/3/thumbnail.jpg"))
                .body("products[2].images.size()", equalTo(1))
                .body("products[2].images[0]", equalTo("https://i.dummyjson.com/data/products/3/1.jpg"))


                .body("products[3].id", equalTo(4))
                .body("products[3].title", equalTo("OPPOF19"))
                .body("products[3].description", equalTo("OPPO F19 is officially announced on April 2021."))
                .body("products[3].price", equalTo(280))
                .body("products[3].discountPercentage", equalTo(17.91))
                .body("products[3].rating", equalTo(4.3))
                .body("products[3].stock", equalTo(123))
                .body("products[3].brand", equalTo("OPPO"))
                .body("products[3].category", equalTo("smartphones"))
                .body("products[3].thumbnail", equalTo("https://i.dummyjson.com/data/products/4/thumbnail.jpg"))
                .body("products[3].images.size()", equalTo(4))
                .body("products[3].images[0]", equalTo("https://i.dummyjson.com/data/products/4/1.jpg"))
                .body("products[3].images[1]", equalTo("https://i.dummyjson.com/data/products/4/2.jpg"))
                .body("products[3].images[2]", equalTo("https://i.dummyjson.com/data/products/4/3.jpg"))
                .body("products[3].images[3]", equalTo("https://i.dummyjson.com/data/products/4/thumbnail.jpg"))


                .body("products[4].id", equalTo(5))
                .body("products[4].title", equalTo("Huawei P30"))
                .body("products[4].description", equalTo("Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK."))
                .body("products[4].price", equalTo(499))
                .body("products[4].discountPercentage", equalTo(10.58))
                .body("products[4].rating", equalTo(4.09))
                .body("products[4].stock", equalTo(32))
                .body("products[4].brand", equalTo("Huawei"))
                .body("products[4].category", equalTo("smartphones"))
                .body("products[4].thumbnail", equalTo("https://i.dummyjson.com/data/products/5/thumbnail.jpg"))
                .body("products[4].images.size()", equalTo(3))
                .body("products[4].images[0]", equalTo("https://i.dummyjson.com/data/products/5/1.jpg"))
                .body("products[4].images[1]", equalTo("https://i.dummyjson.com/data/products/5/2.jpg"))
                .body("products[4].images[2]", equalTo("https://i.dummyjson.com/data/products/5/3.jpg"))


                .body("products[5].id", equalTo(6))
                .body("products[5].title", equalTo("MacBook Pro"))
                .body("products[5].description", equalTo("MacBook Pro 2021 with mini-LED display may launch between September, November"))
                .body("products[5].price", equalTo(1749))
                .body("products[5].discountPercentage", equalTo(11.02))
                .body("products[5].rating", equalTo(4.57))
                .body("products[5].stock", equalTo(83))
                .body("products[5].brand", equalTo("Apple"))
                .body("products[5].category", equalTo("laptops"))
                .body("products[5].thumbnail", equalTo("https://i.dummyjson.com/data/products/6/thumbnail.jpg"))
                .body("products[5].images.size()", equalTo(4))
                .body("products[5].images[0]", equalTo("https://i.dummyjson.com/data/products/6/1.png"))
                .body("products[5].images[1]", equalTo("https://i.dummyjson.com/data/products/6/2.jpg"))
                .body("products[5].images[2]", equalTo("https://i.dummyjson.com/data/products/6/3.png"))
                .body("products[5].images[3]", equalTo("https://i.dummyjson.com/data/products/6/4.jpg"))


                .body("products[6].id", equalTo(7))
                .body("products[6].title", equalTo("Samsung Galaxy Book"))
                .body("products[6].description", equalTo("Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched"))
                .body("products[6].price", equalTo(1499))
                .body("products[6].discountPercentage", equalTo(4.15))
                .body("products[6].rating", equalTo(4.25))
                .body("products[6].stock", equalTo(50))
                .body("products[6].brand", equalTo("Samsung"))
                .body("products[6].category", equalTo("laptops"))
                .body("products[6].thumbnail", equalTo("https://i.dummyjson.com/data/products/7/thumbnail.jpg"))
                .body("products[6].images.size()", equalTo(4))
                .body("products[6].images[0]", equalTo("https://i.dummyjson.com/data/products/7/1.jpg"))
                .body("products[6].images[1]", equalTo("https://i.dummyjson.com/data/products/7/2.jpg"))
                .body("products[6].images[2]", equalTo("https://i.dummyjson.com/data/products/7/3.jpg"))
                .body("products[6].images[3]", equalTo("https://i.dummyjson.com/data/products/7/thumbnail.jpg"))


                .body("products[7].id", equalTo(8))
                .body("products[7].title", equalTo("Microsoft Surface Laptop 4"))
                .body("products[7].description", equalTo("Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen."))
                .body("products[7].price", equalTo(1499))
                .body("products[7].discountPercentage", equalTo(10.23))
                .body("products[7].rating", equalTo(4.43))
                .body("products[7].stock", equalTo(68))
                .body("products[7].brand", equalTo("Microsoft Surface"))
                .body("products[7].category", equalTo("laptops"))
                .body("products[7].thumbnail", equalTo("https://i.dummyjson.com/data/products/8/thumbnail.jpg"))
                .body("products[7].images.size()", equalTo(5))
                .body("products[7].images[0]", equalTo("https://i.dummyjson.com/data/products/8/1.jpg"))
                .body("products[7].images[1]", equalTo("https://i.dummyjson.com/data/products/8/2.jpg"))
                .body("products[7].images[2]", equalTo("https://i.dummyjson.com/data/products/8/3.jpg"))
                .body("products[7].images[3]", equalTo("https://i.dummyjson.com/data/products/8/4.jpg"))
                .body("products[7].images[4]", equalTo("https://i.dummyjson.com/data/products/8/thumbnail.jpg"))


                .body("products[8].id", equalTo(9))
                .body("products[8].title", equalTo("Infinix INBOOK"))
                .body("products[8].description", equalTo("Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty"))
                .body("products[8].price", equalTo(1099))
                .body("products[8].discountPercentage", equalTo(11.83))
                .body("products[8].rating", equalTo(4.54))
                .body("products[8].stock", equalTo(96))
                .body("products[8].brand", equalTo("Infinix"))
                .body("products[8].category", equalTo("laptops"))
                .body("products[8].thumbnail", equalTo("https://i.dummyjson.com/data/products/9/thumbnail.jpg"))
                .body("products[8].images.size()", equalTo(5))
                .body("products[8].images[0]", equalTo("https://i.dummyjson.com/data/products/9/1.jpg"))
                .body("products[8].images[1]", equalTo("https://i.dummyjson.com/data/products/9/2.png"))
                .body("products[8].images[2]", equalTo("https://i.dummyjson.com/data/products/9/3.png"))
                .body("products[8].images[3]", equalTo("https://i.dummyjson.com/data/products/9/4.jpg"))
                .body("products[8].images[4]", equalTo("https://i.dummyjson.com/data/products/9/thumbnail.jpg"))
                .body("products[9].id", equalTo(10))
                .body("products[9].title", equalTo("HP Pavilion 15-DK1056WM"))
                .body("products[9].description", equalTo("HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10"))
                .body("products[9].price", equalTo(1099))
                .body("products[9].discountPercentage", equalTo(6.18))
                .body("products[9].rating", equalTo(4.43))
                .body("products[9].stock", equalTo(89))
                .body("products[9].brand", equalTo("HP Pavilion"))
                .body("products[9].category", equalTo("laptops"))
                .body("products[9].thumbnail", equalTo("https://i.dummyjson.com/data/products/10/thumbnail.jpg"))
                .body("products[9].images.size()", equalTo(4))
                .body("products[9].images[0]", equalTo("https://i.dummyjson.com/data/products/10/1.jpg"))
                .body("products[9].images[1]", equalTo("https://i.dummyjson.com/data/products/10/2.jpg"))
                .body("products[9].images[2]", equalTo("https://i.dummyjson.com/data/products/10/3.jpg"))
                .body("products[9].images[3]", equalTo("https://i.dummyjson.com/data/products/10/thumbnail.jpeg"))


                .body("products[10].id", equalTo(11))
                .body("products[10].title", equalTo("perfume Oil"))
                .body("products[10].description", equalTo("Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil"))
                .body("products[10].price", equalTo(13))
                .body("products[10].discountPercentage", equalTo(8.4))
                .body("products[10].rating", equalTo(4.26))
                .body("products[10].stock", equalTo(65))
                .body("products[10].brand", equalTo("Impression of Acqua Di Gio"))
                .body("products[10].category", equalTo("fragrances"))
                .body("products[10].thumbnail", equalTo("https://i.dummyjson.com/data/products/11/thumbnail.jpg"))
                .body("products[10].images.size()", equalTo(4))
                .body("products[10].images[0]", equalTo("https://i.dummyjson.com/data/products/11/1.jpg"))
                .body("products[10].images[1]", equalTo("https://i.dummyjson.com/data/products/11/2.jpg"))
                .body("products[10].images[2]", equalTo("https://i.dummyjson.com/data/products/11/3.jpg"))
                .body("products[10].images[3]", equalTo("https://i.dummyjson.com/data/products/11/thumbnail.jpg"))


                .body("products[11].id", equalTo(12))
                .body("products[11].title", equalTo("Brown Perfume"))
                .body("products[11].description", equalTo("Royal_Mirage Sport Brown Perfume for Men & Women - 120ml"))
                .body("products[11].price", equalTo(40))
                .body("products[11].discountPercentage", equalTo(15.66))
                .body("products[11].rating", equalTo(4))
                .body("products[11].stock", equalTo(52))
                .body("products[11].brand", equalTo("Royal_Mirage"))
                .body("products[11].category", equalTo("fragrances"))
                .body("products[11].thumbnail", equalTo("https://i.dummyjson.com/data/products/12/thumbnail.jpg"))
                .body("products[11].images.size()", equalTo(5))
                .body("products[11].images[0]", equalTo("https://i.dummyjson.com/data/products/12/1.jpg"))
                .body("products[11].images[1]", equalTo("https://i.dummyjson.com/data/products/12/2.jpg"))
                .body("products[11].images[2]", equalTo("https://i.dummyjson.com/data/products/12/3.png"))
                .body("products[11].images[3]", equalTo("https://i.dummyjson.com/data/products/12/4.jpg"))
                .body("products[11].images[4]", equalTo("https://i.dummyjson.com/data/products/12/thumbnail.jpg"))


                .body("products[12].id", equalTo(13))
                .body("products[12].title", equalTo("Fog Scent Xpressio Perfume"))
                .body("products[12].description", equalTo("Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men"))
                .body("products[12].price", equalTo(13))
                .body("products[12].discountPercentage", equalTo(8.14))
                .body("products[12].rating", equalTo(4.59))
                .body("products[12].stock", equalTo(61))
                .body("products[12].brand", equalTo("Fog Scent Xpressio"))
                .body("products[12].category", equalTo("fragrances"))
                .body("products[12].thumbnail", equalTo("https://i.dummyjson.com/data/products/13/thumbnail.jpg"))
                .body("products[12].images.size()", equalTo(5))
                .body("products[12].images[0]", equalTo("https://i.dummyjson.com/data/products/13/1.jpg"))
                .body("products[12].images[1]", equalTo("https://i.dummyjson.com/data/products/13/2.png"))
                .body("products[12].images[2]", equalTo("https://i.dummyjson.com/data/products/13/3.jpg"))
                .body("products[12].images[3]", equalTo("https://i.dummyjson.com/data/products/13/4.jpg"))
                .body("products[12].images[4]", equalTo("https://i.dummyjson.com/data/products/13/thumbnail.webp"))


                .body("products[13].id", equalTo(14))
                .body("products[13].title", equalTo("Non-Alcoholic Concentrated Perfume Oil"))
                .body("products[13].description", equalTo("Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil"))
                .body("products[13].price", equalTo(120))
                .body("products[13].discountPercentage", equalTo(15.6))
                .body("products[13].rating", equalTo(4.21))
                .body("products[13].stock", equalTo(114))
                .body("products[13].brand", equalTo("Al Munakh"))
                .body("products[13].category", equalTo("fragrances"))
                .body("products[13].thumbnail", equalTo("https://i.dummyjson.com/data/products/14/thumbnail.jpg"))
                .body("products[13].images.size()", equalTo(4))
                .body("products[13].images[0]", equalTo("https://i.dummyjson.com/data/products/14/1.jpg"))
                .body("products[13].images[1]", equalTo("https://i.dummyjson.com/data/products/14/2.jpg"))
                .body("products[13].images[2]", equalTo("https://i.dummyjson.com/data/products/14/3.jpg"))
                .body("products[13].images[3]", equalTo("https://i.dummyjson.com/data/products/14/thumbnail.jpg"))


                .body("products[14].id", equalTo(15))
                .body("products[14].title", equalTo("Eau De Perfume Spray"))
                .body("products[14].description", equalTo("Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality"))
                .body("products[14].price", equalTo(30))
                .body("products[14].discountPercentage", equalTo(10.99))
                .body("products[14].rating", equalTo(4.7))
                .body("products[14].stock", equalTo(105))
                .body("products[14].brand", equalTo("Lord - Al-Rehab"))
                .body("products[14].category", equalTo("fragrances"))
                .body("products[14].thumbnail", equalTo("https://i.dummyjson.com/data/products/15/thumbnail.jpg"))
                .body("products[14].images.size()", equalTo(5))
                .body("products[14].images[0]", equalTo("https://i.dummyjson.com/data/products/15/1.jpg"))
                .body("products[14].images[1]", equalTo("https://i.dummyjson.com/data/products/15/2.jpg"))
                .body("products[14].images[2]", equalTo("https://i.dummyjson.com/data/products/15/3.jpg"))
                .body("products[14].images[3]", equalTo("https://i.dummyjson.com/data/products/15/4.jpg"))
                .body("products[14].images[4]", equalTo("https://i.dummyjson.com/data/products/15/thumbnail.jpg"))


                .body("products[15].id", equalTo(16))
                .body("products[15].title", equalTo("Hyaluronic Acid Serum"))
                .body("products[15].description", equalTo("L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid"))
                .body("products[15].price", equalTo(19))
                .body("products[15].discountPercentage", equalTo(13.31))
                .body("products[15].rating", equalTo(4.83))
                .body("products[15].stock", equalTo(110))
                .body("products[15].brand", equalTo("L'Oreal Paris"))
                .body("products[15].category", equalTo("skincare"))
                .body("products[15].thumbnail", equalTo("https://i.dummyjson.com/data/products/16/thumbnail.jpg"))
                .body("products[15].images.size()", equalTo(5))
                .body("products[15].images[0]", equalTo("https://i.dummyjson.com/data/products/16/1.png"))
                .body("products[15].images[1]", equalTo("https://i.dummyjson.com/data/products/16/2.webp"))
                .body("products[15].images[2]", equalTo("https://i.dummyjson.com/data/products/16/3.jpg"))
                .body("products[15].images[3]", equalTo("https://i.dummyjson.com/data/products/16/4.jpg"))
                .body("products[15].images[4]", equalTo("https://i.dummyjson.com/data/products/16/thumbnail.jpg"))


                .body("products[16].id", equalTo(17))
                .body("products[16].title", equalTo("Tree Oil 30ml"))
                .body("products[16].description", equalTo("Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,"))
                .body("products[16].price", equalTo(12))
                .body("products[16].discountPercentage", equalTo(4.09))
                .body("products[16].rating", equalTo(4.52))
                .body("products[16].stock", equalTo(78))
                .body("products[16].brand", equalTo("Hemani Tea"))
                .body("products[16].category", equalTo("skincare"))
                .body("products[16].thumbnail", equalTo("https://i.dummyjson.com/data/products/17/thumbnail.jpg"))
                .body("products[16].images.size()", equalTo(4))
                .body("products[16].images[0]", equalTo("https://i.dummyjson.com/data/products/17/1.jpg"))
                .body("products[16].images[1]", equalTo("https://i.dummyjson.com/data/products/17/2.jpg"))
                .body("products[16].images[2]", equalTo("https://i.dummyjson.com/data/products/17/3.jpg"))
                .body("products[16].images[3]", equalTo("https://i.dummyjson.com/data/products/17/thumbnail.jpg"))


                .body("products[17].id", equalTo(18))
                .body("products[17].title", equalTo("Oil Free Moisturizer 100ml"))
                .body("products[17].description", equalTo("Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen."))
                .body("products[17].price", equalTo(40))
                .body("products[17].discountPercentage", equalTo(13.1))
                .body("products[17].rating", equalTo(4.56))
                .body("products[17].stock", equalTo(88))
                .body("products[17].brand", equalTo("Dermive"))
                .body("products[17].category", equalTo("skincare"))
                .body("products[17].thumbnail", equalTo("https://i.dummyjson.com/data/products/18/thumbnail.jpg"))
                .body("products[17].images.size()", equalTo(5))
                .body("products[17].images[0]", equalTo("https://i.dummyjson.com/data/products/18/1.jpg"))
                .body("products[17].images[1]", equalTo("https://i.dummyjson.com/data/products/18/2.jpg"))
                .body("products[17].images[2]", equalTo("https://i.dummyjson.com/data/products/18/3.jpg"))
                .body("products[17].images[3]", equalTo("https://i.dummyjson.com/data/products/18/4.jpg"))
                .body("products[17].images[4]", equalTo("https://i.dummyjson.com/data/products/18/thumbnail.jpg"))


                .body("products[18].id", equalTo(19))
                .body("products[18].title", equalTo("Skin Beauty Serum."))
                .body("products[18].description", equalTo("Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m"))
                .body("products[18].price", equalTo(46))
                .body("products[18].discountPercentage", equalTo(10.68))
                .body("products[18].rating", equalTo(4.42))
                .body("products[18].stock", equalTo(54))
                .body("products[18].brand", equalTo("ROREC White Rice"))
                .body("products[18].category", equalTo("skincare"))
                .body("products[18].thumbnail", equalTo("https://i.dummyjson.com/data/products/18/thumbnail.jpg"))
                .body("products[18].images.size()", equalTo(4))
                .body("products[18].images[0]", equalTo("https://i.dummyjson.com/data/products/19/1.jpg"))
                .body("products[18].images[1]", equalTo("https://i.dummyjson.com/data/products/19/2.jpg"))
                .body("products[18].images[2]", equalTo("https://i.dummyjson.com/data/products/19/3.png"))
                .body("products[18].images[3]", equalTo("https://i.dummyjson.com/data/products/19/thumbnail.jpg"))


                .body("products[19].id", equalTo(20))
                .body("products[19].title", equalTo("Freckle Treatment Cream- 15gm"))
                .body("products[19].description", equalTo("Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects."))
                .body("products[19].price", equalTo(70))
                .body("products[19].discountPercentage", equalTo(16.99))
                .body("products[19].rating", equalTo(4.06))
                .body("products[19].stock", equalTo(140))
                .body("products[19].brand", equalTo("Fair & Clear"))
                .body("products[19].category", equalTo("skincare"))
                .body("products[19].thumbnail", equalTo("https://i.dummyjson.com/data/products/20/thumbnail.jpg"))
                .body("products[19].images.size()", equalTo(5))
                .body("products[19].images[0]", equalTo("https://i.dummyjson.com/data/products/20/1.jpg"))
                .body("products[19].images[1]", equalTo("https://i.dummyjson.com/data/products/20/2.jpg"))
                .body("products[19].images[2]", equalTo("https://i.dummyjson.com/data/products/20/3.jpg"))
                .body("products[19].images[3]", equalTo("https://i.dummyjson.com/data/products/20/4.jpg"))
                .body("products[19].images[4]", equalTo("https://i.dummyjson.com/data/products/20/thumbnail.jpg"))


                .body("products[20].id", equalTo(21))
                .body("products[20].title", equalTo("- Daal Masoor 500 grams"))
                .body("products[20].description", equalTo("Fine quality Branded Product Keep in a cool and dry place"))
                .body("products[20].price", equalTo(20))
                .body("products[20].discountPercentage", equalTo(4.81))
                .body("products[20].rating", equalTo(4.44))
                .body("products[20].stock", equalTo(133))
                .body("products[20].brand", equalTo("Saaf & Khaas"))
                .body("products[20].category", equalTo("groceries"))
                .body("products[20].thumbnail", equalTo("https://i.dummyjson.com/data/products/21/thumbnail.jpg"))
                .body("products[20].images.size()", equalTo(3))
                .body("products[20].images[0]", equalTo("https://i.dummyjson.com/data/products/21/1.png"))
                .body("products[20].images[1]", equalTo("https://i.dummyjson.com/data/products/21/2.jpg"))
                .body("products[20].images[2]", equalTo("https://i.dummyjson.com/data/products/21/3.jpg"))
                .body("products[21].id", equalTo(22))
                .body("products[21].title", equalTo("Elbow Macaroni - 400 gm"))
                .body("products[21].description", equalTo("Product details of Bake Parlor Big Elbow Macaroni - 400 gm"))
                .body("products[21].price", equalTo(14))
                .body("products[21].discountPercentage", equalTo(15.58))
                .body("products[21].rating", equalTo(4.57))
                .body("products[21].stock", equalTo(146))
                .body("products[21].brand", equalTo("Bake Parlor Big"))
                .body("products[21].category", equalTo("groceries"))
                .body("products[21].thumbnail", equalTo("https://i.dummyjson.com/data/products/22/thumbnail.jpg"))
                .body("products[21].images.size()", equalTo(3))
                .body("products[21].images[0]", equalTo("https://i.dummyjson.com/data/products/22/1.jpg"))
                .body("products[21].images[1]", equalTo("https://i.dummyjson.com/data/products/22/2.jpg"))
                .body("products[21].images[2]", equalTo("https://i.dummyjson.com/data/products/22/3.jpg"))


                .body("products[22].id", equalTo(23))
                .body("products[22].title", equalTo("Orange Essence Food Flavou"))
                .body("products[22].description", equalTo("Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item"))
                .body("products[22].price", equalTo(14))
                .body("products[22].discountPercentage", equalTo(8.04))
                .body("products[22].rating", equalTo(4.85))
                .body("products[22].stock", equalTo(26))
                .body("products[22].brand", equalTo("Baking Food Items"))
                .body("products[22].category", equalTo("groceries"))
                .body("products[22].thumbnail", equalTo("https://i.dummyjson.com/data/products/23/thumbnail.jpg"))
                .body("products[22].images.size()", equalTo(5))
                .body("products[22].images[0]", equalTo("https://i.dummyjson.com/data/products/23/1.jpg"))
                .body("products[22].images[1]", equalTo("https://i.dummyjson.com/data/products/23/2.jpg"))
                .body("products[22].images[2]", equalTo("https://i.dummyjson.com/data/products/23/3.jpg"))
                .body("products[22].images[3]", equalTo("https://i.dummyjson.com/data/products/23/4.jpg"))
                .body("products[22].images[4]", equalTo("https://i.dummyjson.com/data/products/23/thumbnail.jpg"))


                .body("products[23].id", equalTo(24))
                .body("products[23].title", equalTo("cereals muesli fruit nuts"))
                .body("products[23].description", equalTo("original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji"))
                .body("products[23].price", equalTo(46))
                .body("products[23].discountPercentage", equalTo(16.8))
                .body("products[23].rating", equalTo(4.94))
                .body("products[23].stock", equalTo(113))
                .body("products[23].brand", equalTo("fauji"))
                .body("products[23].category", equalTo("groceries"))
                .body("products[23].thumbnail", equalTo("https://i.dummyjson.com/data/products/24/thumbnail.jpg"))
                .body("products[23].images.size()", equalTo(5))
                .body("products[23].images[0]", equalTo("https://i.dummyjson.com/data/products/24/1.jpg"))
                .body("products[23].images[1]", equalTo("https://i.dummyjson.com/data/products/24/2.jpg"))
                .body("products[23].images[2]", equalTo("https://i.dummyjson.com/data/products/24/3.jpg"))
                .body("products[23].images[3]", equalTo("https://i.dummyjson.com/data/products/24/4.jpg"))
                .body("products[23].images[4]", equalTo("https://i.dummyjson.com/data/products/24/thumbnail.jpg"))


                .body("products[24].id", equalTo(25))
                .body("products[24].title", equalTo("Gulab Powder 50 Gram"))
                .body("products[24].description", equalTo("Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds"))
                .body("products[24].price", equalTo(70))
                .body("products[24].discountPercentage", equalTo(13.58))
                .body("products[24].rating", equalTo(4.87))
                .body("products[24].stock", equalTo(47))
                .body("products[24].brand", equalTo("Dry Rose"))
                .body("products[24].category", equalTo("groceries"))
                .body("products[24].thumbnail", equalTo("https://i.dummyjson.com/data/products/25/thumbnail.jpg"))
                .body("products[24].images.size()", equalTo(5))
                .body("products[24].images[0]", equalTo("https://i.dummyjson.com/data/products/25/1.png"))
                .body("products[24].images[1]", equalTo("https://i.dummyjson.com/data/products/25/2.jpg"))
                .body("products[24].images[2]", equalTo("https://i.dummyjson.com/data/products/25/3.png"))
                .body("products[24].images[3]", equalTo("https://i.dummyjson.com/data/products/25/4.jpg"))
                .body("products[24].images[4]", equalTo("https://i.dummyjson.com/data/products/25/thumbnail.jpg"))


                .body("products[25].id", equalTo(26))
                .body("products[25].title", equalTo("Plant Hanger For Home"))
                .body("products[25].description", equalTo("Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf"))
                .body("products[25].price", equalTo(41))
                .body("products[25].discountPercentage", equalTo(17.86))
                .body("products[25].rating", equalTo(4.08))
                .body("products[25].stock", equalTo(131))
                .body("products[25].brand", equalTo("Boho Decor"))
                .body("products[25].category", equalTo("home-decoration"))
                .body("products[25].thumbnail", equalTo("https://i.dummyjson.com/data/products/26/thumbnail.jpg"))
                .body("products[25].images.size()", equalTo(6))
                .body("products[25].images[0]", equalTo("https://i.dummyjson.com/data/products/26/1.jpg"))
                .body("products[25].images[1]", equalTo("https://i.dummyjson.com/data/products/26/2.jpg"))
                .body("products[25].images[2]", equalTo("https://i.dummyjson.com/data/products/26/3.jpg"))
                .body("products[25].images[3]", equalTo("https://i.dummyjson.com/data/products/26/4.jpg"))
                .body("products[25].images[4]", equalTo("https://i.dummyjson.com/data/products/26/5.jpg"))
                .body("products[25].images[5]", equalTo("https://i.dummyjson.com/data/products/26/thumbnail.jpg"))


                .body("products[26].id", equalTo(27))
                .body("products[26].title", equalTo("Flying Wooden Bird"))
                .body("products[26].description", equalTo("Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm"))
                .body("products[26].price", equalTo(51))
                .body("products[26].discountPercentage", equalTo(15.58))
                .body("products[26].rating", equalTo(4.41))
                .body("products[26].stock", equalTo(17))
                .body("products[26].brand", equalTo("Flying Wooden"))
                .body("products[26].category", equalTo("home-decoration"))
                .body("products[26].thumbnail", equalTo("https://i.dummyjson.com/data/products/27/thumbnail.jpg"))
                .body("products[26].images.size()", equalTo(5))
                .body("products[26].images[0]", equalTo("https://i.dummyjson.com/data/products/27/1.jpg"))
                .body("products[26].images[1]", equalTo("https://i.dummyjson.com/data/products/27/2.jpg"))
                .body("products[26].images[2]", equalTo("https://i.dummyjson.com/data/products/27/3.jpg"))
                .body("products[26].images[3]", equalTo("https://i.dummyjson.com/data/products/27/4.jpg"))
                .body("products[26].images[4]", equalTo("https://i.dummyjson.com/data/products/27/thumbnail.webp"))


                .body("products[27].id", equalTo(28))
                .body("products[27].title", equalTo("3D Embellishment Art Lamp"))
                .body("products[27].description", equalTo("3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)"))
                .body("products[27].price", equalTo(20))
                .body("products[27].discountPercentage", equalTo(16.49))
                .body("products[27].rating", equalTo(4.82))
                .body("products[27].stock", equalTo(54))
                .body("products[27].brand", equalTo("LED Lights"))
                .body("products[27].category", equalTo("home-decoration"))
                .body("products[27].thumbnail", equalTo("https://i.dummyjson.com/data/products/28/thumbnail.jpg"))
                .body("products[27].images.size()", equalTo(5))
                .body("products[27].images[0]", equalTo("https://i.dummyjson.com/data/products/28/1.jpg"))
                .body("products[27].images[1]", equalTo("https://i.dummyjson.com/data/products/28/2.jpg"))
                .body("products[27].images[2]", equalTo("https://i.dummyjson.com/data/products/28/3.png"))
                .body("products[27].images[3]", equalTo("https://i.dummyjson.com/data/products/28/4.jpg"))
                .body("products[27].images[4]", equalTo("https://i.dummyjson.com/data/products/28/thumbnail.jpg"))


                .body("products[28].id", equalTo(29))
                .body("products[28].title", equalTo("Handcraft Chinese style"))
                .body("products[28].description", equalTo("Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate"))
                .body("products[28].price", equalTo(60))
                .body("products[28].discountPercentage", equalTo(15.34))
                .body("products[28].rating", equalTo(4.44))
                .body("products[28].stock", equalTo(7))
                .body("products[28].brand", equalTo("luxury palace"))
                .body("products[28].category", equalTo("home-decoration"))
                .body("products[28].thumbnail", equalTo("https://i.dummyjson.com/data/products/29/thumbnail.jpg"))
                .body("products[28].images.size()", equalTo(5))
                .body("products[28].images[0]", equalTo("https://i.dummyjson.com/data/products/29/1.jpg"))
                .body("products[28].images[1]", equalTo("https://i.dummyjson.com/data/products/29/2.jpg"))
                .body("products[28].images[2]", equalTo("https://i.dummyjson.com/data/products/29/3.webp"))
                .body("products[28].images[3]", equalTo("https://i.dummyjson.com/data/products/29/4.webp"))
                .body("products[28].images[4]", equalTo("https://i.dummyjson.com/data/products/29/thumbnail.webp"))


                .body("products[29].id", equalTo(30))
                .body("products[29].title", equalTo("Key Holder"))
                .body("products[29].description", equalTo("Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality"))
                .body("products[29].price", equalTo(30))
                .body("products[29].discountPercentage", equalTo(2.92))
                .body("products[29].rating", equalTo(4.92))
                .body("products[29].stock", equalTo(54))
                .body("products[29].brand", equalTo("Golden"))
                .body("products[29].category", equalTo("home-decoration"))
                .body("products[29].thumbnail", equalTo("https://i.dummyjson.com/data/products/30/thumbnail.jpg"))
                .body("products[29].images.size()", equalTo(4))
                .body("products[29].images[0]", equalTo("https://i.dummyjson.com/data/products/30/1.jpg"))
                .body("products[29].images[1]", equalTo("https://i.dummyjson.com/data/products/30/2.jpg"))
                .body("products[29].images[2]", equalTo("https://i.dummyjson.com/data/products/30/3.jpg"))
                .body("products[29].images[3]", equalTo("https://i.dummyjson.com/data/products/30/thumbnail.jpg"))


                .body("total", equalTo(100))
                .body("skip", equalTo(0))
                .body("limit", equalTo(30));

    }

}
